package Exception;

public class throesdemo {
	void display()throws ArithmeticException{
		int a=20,b=0,c;
		c=a/b;
		System.out.println(c);
		}
	

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		throesdemo in=new throesdemo();
		try{
			in.display();
		}
		catch(Exception ae){
			System.out.println(" ArithmeticException occur"+ae.getMessage());
		}
		System.out.println("normal flow");
	}

}
